module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'false',
    AUTO_LIKE_EMOJI: ['🌸', '🪴', '💫', '🍂', '🌟','🫀', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/D6V9iJU6Fte8u6byru7lWr?mode=gi_c',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/v5k6lz.jpg',
    NEWSLETTER_JID: '120363401814154475@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: '𝓩𝓪𝓷𝓽𝓪 𝔁𝓶𝓭 𝓵𝓲𝓽𝓮',
    OWNER_NAME: 'ᥫ᭡ Rᴀᴍᴇꜱʜ ꜱᴀᴍᴘᴀᴛʜ 🙈🤍✨',
    OWNER_NUMBER: '94766002356',
    BOT_VERSION: '1.0.2',
    BOT_FOOTER: '> ᴘᴏᴡᴇʀᴇᴅ ʙʏ ᥫ᭡ Rᴀᴍᴇꜱʜ ꜱᴀᴍᴘᴀᴛʜ 🙈🤍✨',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029VbBBr1iElagw9wIc9K3M',
};
